### PR TITLE
Adding in Main branch for new users

### PR DESCRIPTION
**Pull request by fawazsiddiqi**
Trigger action if branch is main as well

### CODE REVIEW

**Comment by fawazsiddiqi** [comment]
Test failing due to incorrect credentials on my end for the repo

**Comment by fawazsiddiqi** [comment]
Build passing now

**Comment by teoxoy** [comment]
I don't think it's necessary to update `test.yml`. The change should only affect the example in the readme.

**Comment by fawazsiddiqi** [comment]
Will make the change in a while

**Comment by fawazsiddiqi** [comment]
@teoxoy done, reverted test.yml to original form and only updated the readme example

**Comment by fawazsiddiqi** [comment]
Test passed in my repo, failing here due to user_token

**Pull request merged**
